[#63] Adding documentation files
Software-For-Love/humans pull request #96
Opened 2022-03-31 22:57 UTC by JKal24

Added markdown files to indicate how changes should be made to the deployed site, how to handle currently featured and all featured data & how to format the data.
Also added some markdown files explaining the forms on the site, their layout and what they should be used for.
Created a template Yaml file that can be filled out and placed in the data folder as a currently featured Yaml file.

2022-04-02 20:11 UTC, dhari001 commented on docs/deploy.md
> +
for some people they'll be updating for the first time and they're going to need an indication that they should clone the repo first so just add a brief instruction about that

2022-04-02 20:14 UTC, dhari001 commented on docs/feature.md
> +The ID is represented as `Date_FirstNameLastName` in the Yaml file and the file name will be `DateFirstNameLastName.yaml`
what is the format of the date? is it just DD/MM/YYYY or is it in words so "April2nd2022". Specify date format.

2022-04-02 20:15 UTC, dhari001 commented on docs/feature.md
> +The ID is represented as `Date_FirstNameLastName` in the Yaml file and the file name will be `DateFirstNameLastName.yaml`
nvm see the format below

2022-04-03 06:19 UTC, Fatimbit requested changes
This is really good! It's great how thorough you are with the instructions to even explain stuff like using cmd and cd path commands and it's very clear and easy to follow. I also thought that having a separate template file was a good idea. 
There are 2 things that should be taken care of before we merge this, which I'm listing below, but this is overall very good!
1. I agree with what Dharitri said about adding a brief instruction about cloning the repo first for people updating for the first time
2. in deploy.md on line 23 it talks about cloning with `git clone https://github.com/Software-For-Love`, but shouldn't that be 'https://github.com/Software-For-Love/humans.git' if they're just trying to clone into our repo for humans

2022-04-03 22:57 UTC, Fatimbit approved these changes
Nice work, thank you!

2022-04-03 22:57 UTC, merged